//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.DICHVUDADATs = new HashSet<DICHVUDADAT>();
        }
    
        public int MAHD { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MAPHIEUDAT { get; set; }
        public Nullable<System.DateTime> NGAYTRAPHONG { get; set; }
        public Nullable<decimal> TIENPHONG { get; set; }
        public Nullable<decimal> TIENDICHVU { get; set; }
        public Nullable<decimal> PHUTHU { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> TINHTRANGHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICHVUDADAT> DICHVUDADATs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEUDATPHONG PHIEUDATPHONG { get; set; }
    }
}
