//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.PHIEUDATPHONGs = new HashSet<PHIEUDATPHONG>();
        }
    
        public int MAPHONG { get; set; }
        public Nullable<int> MATANG { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public string SOPHONG { get; set; }
        public Nullable<int> TINHTRANGPHONG { get; set; }
    
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATPHONG> PHIEUDATPHONGs { get; set; }
        public virtual TANG TANG { get; set; }
    }
}
